### ISSUE TITLE
default attributes

### ISSUE THREAD

**Issue by cjessett** [ShaggyDude/pjs-capstone-lodash#3]
(Simplify) [Here](https://github.com/ShaggyDude/pjs-capstone-lodash/blob/e41278745f555612222009392692248488e67446/lodash/_.js#L17-L20) instead of assigning default values here, assign them in the arguments. Like,
```
inRange: (number, start = 0, end = start)
```

**Comment by ShaggyDude** [comment]
Fixed in https://github.com/ShaggyDude/pjs-capstone-lodash/commit/b27bd9e802ff359ea4724b63c172fb0933067771
